options:
  version:
    type: string
    default: "1.7"
    description: "Version of HAProxy to install"
  enable-stats:
    type: boolean
    default: True
    description: "Enable HAProxy stats page"
  stats-user:
    type: string
    default: "admin"
    description: "Username for accessing stats page"
  stats-passwd:
    type: string
    default: "admin"
    description: "Password for accessing stats page"
  stats-url:
    type: string
    default: "/ha-stats"
    description: "URL for accessing stats page"
  stats-port:
    type: int
    default: 9000
    description: "Port for accessing stats page"
  stats-local:
    type: boolean
    default: True
    description: "Restrict stats to local IP ranges"
  cert-renew-interval:
    type: string
    default: "@daily"
    description: "Cron interval for letsencrypt renew, if in use"
  upnp-renew-interval:
    type: string
    default: '@hourly'
    description: "Cron interval to rewnew upnp, if in use"
  destination-https-rewrite:
    type: boolean
    default: True
    description: "Rewrite 'Destination' header so WebDav servers wont fail on mismatched file paths (http vs https)"
  enable-https-redirect:
    type: boolean
    default: True
    description: "Redirect http requets with no explicit backend to https"
