#!/usr/local/sbin/charm-env python3

from charmhelpers.core import hookenv
import sys
sys.path.append(hookenv.charm_dir())
sys.path.append(hookenv.charm_dir() + '/lib')

from libhaproxy import ProxyHelper

ph = ProxyHelper()
ph.renew_upnp()

