#!/usr/local/sbin/charm-env python3

from charmhelpers.core import hookenv
import sys
sys.path.append(hookenv.charm_dir())
sys.path.append(hookenv.charm_dir() + '/lib')

from libhaproxy import ProxyHelper

# This is an ugly hack to allow juju-run to call from cron
try:
    full = hookenv.action_get('full')
except:
    full = False

hookenv.log("Calling with full= {}".format(full), 'DEBUG')
ph = ProxyHelper()
ph.renew_cert(full=full)

